### ISSUE TITLE
log empty

### ISSUE THREAD

**Issue by jeekajoo** [seeker89/cozy-pfm#47]
Hello,

Log stays empty even when "Internal Server Error" occurs.

```
/usr/local/cozy/apps/pfm/log# ls -l
total 0
-rw-r--r-- 1 cozy-pfm cozy-pfm 0 Feb  1 21:01 production.log
```

What I see on client side:

```
"{"error":"Server error occurred while retrieving data -- Weboob is not available -- null"}"
```

Thanks

**Comment by jeekajoo** [comment]
may be a dup of https://github.com/cozy/cozy-controller/issues/29 ?

**Comment by jsilvestre** [comment]
Hello @jeekajoo and thank you for the report.
There is surely an issue with the fact you can't see the logs, thus we are reported the application not to work anymore. I'm investigating this right now.
Thank you for your patience.

**Comment by jeekajoo** [comment]
yep it doesn't work anymore since January 7th approx. I tried with boursorama and labanquepostale.
Thanks

**Comment by jsilvestre** [comment]
Apparently it's not the application, but the connectors that retrieve the data, that are out of date. I'm still looking at it, waiting for an update of those connectors (see https://github.com/frankrousseau/weboob-modules/issues/1) by @frankrousseau. I keep you updated as I progress.

**Comment by frankrousseau** [comment]
I made the update.

**Comment by jeekajoo** [comment]
Thank you Frank. It works again.

**Comment by jsilvestre** [comment]
I confirm the update fixed it for me too. @frankrousseau did you update @jeekajoo's VM or simply the repo? I don't understand how it can be fixed without an indexer's update.

**Comment by jeekajoo** [comment]
I updated the indexer myself following the documentation (http://cozy.io/host/manage.html#update)
;)

**Comment by jsilvestre** [comment]
Very good, thank you! I'm closing the issue. Let us know if doesn't work again, that could probably mean we need to update it :)

**Comment by frankrousseau** [comment]
Great thank you both for fixing that issue!
